name: CamFly
version: 1.0.0
main: de.elia.cameraplugin.camfly2.CameraPlugin
api-version: 26.2
author: Rexminecraft343
description: A plugin for a camera mode with an armour stand or mannequin body

commands:
  cam:
    description: Enables or disables camera mode
    usage: /<command>
    permission: camplugin.use
    permission-message: "You do not have permission for this command.!"

permissions:
  camplugin.use:
    description: Allows the use of camera mode
    default: true